ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "menuItemId" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "reply" TEXT;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "replyDate" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "Review_menuItemId_idx" ON "Review"("menuItemId");