-- AlterEnum
ALTER TYPE "OtpPurpose" ADD VALUE IF NOT EXISTS 'CUSTOMER_SIGNUP';
ALTER TYPE "OtpPurpose" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET';

-- AlterTable
ALTER TABLE "OtpVerification" ADD COLUMN IF NOT EXISTS "pendingSignupData" JSONB;
