import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Minus, Plus, Trash2, Receipt, ChevronLeft, ChevronDown, ChevronUp } from "lucide-react";
import { getRestaurantById } from "../../services/foodService.js";

const FOOD_GST_RATE = 0.05;
const DELIVERY_GST_RATE = 0.18;
const PLATFORM_FEE = 0;
const PACKAGING_PERCENT = 0.01;

const DELIVERY_SLABS = [
  { maxKm: 1, fee: 17 },
  { maxKm: 2, fee: 23 },
  { maxKm: 3, fee: 30 },
  { maxKm: 4, fee: 35 },
];

const formatCurrency = (amount) => `₹${Math.floor(amount)}`;

const getPrice = (price) => {
  if (typeof price === "number") return price;
  return parseInt(price.toString().replace(/[^0-9]/g, ""), 10) || 0;
};

const calculateDeliveryBase = (distanceKm) => {
  const distance = distanceKm || 1;
  for (const slab of DELIVERY_SLABS) {
    if (distance <= slab.maxKm) return slab.fee;
  }
  const lastSlab = DELIVERY_SLABS[DELIVERY_SLABS.length - 1];
  return lastSlab.fee + Math.ceil(distance - lastSlab.maxKm) * 10;
};

const InvoiceDownload = ({ cart, itemTotal, packagingFeeBase, foodGst, packagingTax, deliveryBase, deliveryGst, platformFee, platformBase, platformTax, totalTax, grandTotal, distanceKm }) => {
  const handleDownload = () => {
    const cgst = totalTax / 2;
    const sgst = totalTax / 2;
    const itemsHtml = cart.map((item, i) =>
      `<tr><td style="padding:8px;border-bottom:1px solid #ddd">${i + 1}</td><td style="padding:8px;border-bottom:1px solid #ddd">${item.name}</td><td style="padding:8px;border-bottom:1px solid #ddd;text-align:center">${item.quantity}</td><td style="padding:8px;border-bottom:1px solid #ddd;text-align:right">₹${getPrice(item.price)}</td><td style="padding:8px;border-bottom:1px solid #ddd;text-align:right">₹${getPrice(item.price) * item.quantity}</td></tr>`
    ).join("");

    const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Invoice - Cravzo</title>
<style>
body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;padding:20px;color:#333}
h1{text-align:center;color:#5b21b6;margin-bottom:4px}
.sub{text-align:center;color:#666;font-size:14px;margin-bottom:30px}
table{width:100%;border-collapse:collapse;margin:20px 0}
th{background:#5b21b6;color:#fff;padding:10px;text-align:left}
td{padding:8px;border-bottom:1px solid #eee}
.totals td{padding:6px 8px;border:none}
.grand td{font-size:18px;font-weight:bold;border-top:2px solid #5b21b6;padding-top:10px}
.footer{text-align:center;margin-top:40px;color:#999;font-size:12px}
.right{text-align:right}
</style></head><body>
<h1>CRAVZO</h1>
<p class="sub">Tax Invoice</p>
<table>
<tr><th>#</th><th>Item</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>
${itemsHtml}
</table>
<table class="totals">
<tr><td><strong>Item Total</strong></td><td class="right">₹${Math.floor(itemTotal)}</td></tr>
<tr><td>Packaging Charge</td><td class="right">₹${Math.floor(packagingFeeBase)}</td></tr>
<tr><td style="padding-top:10px"><strong>Tax Breakdown</strong></td><td></td></tr>
<tr><td style="padding-left:20px">Food GST (5% on items + packaging)</td><td class="right">₹${Math.floor(foodGst + packagingTax)}</td></tr>
<tr><td style="padding-left:20px">Delivery GST (18% on ₹${deliveryBase})</td><td class="right">₹${Math.floor(deliveryGst)}</td></tr>
<tr><td style="padding-left:20px">Platform Fee (₹${platformFee} incl. 18% GST)</td><td class="right">₹${Math.floor(platformFee)}</td></tr>
<tr><td style="padding-left:20px">  Platform Base</td><td class="right">₹${platformBase.toFixed(2)}</td></tr>
<tr><td style="padding-left:20px">  Platform GST @18%</td><td class="right">₹${Math.floor(platformTax)}</td></tr>
<tr><td><strong>Total Tax (GST)</strong></td><td class="right"><strong>₹${Math.floor(totalTax)}</strong></td></tr>
<tr><td style="padding-left:20px">  CGST (50%)</td><td class="right">₹${Math.floor(cgst)}</td></tr>
<tr><td style="padding-left:20px">  SGST (50%)</td><td class="right">₹${Math.floor(sgst)}</td></tr>
<tr class="grand"><td>Grand Total</td><td class="right">₹${Math.floor(grandTotal)}</td></tr>
</table>
<p class="footer">Distance: ${distanceKm ? distanceKm.toFixed(2) : "—"} km | Generated by Cravzo</p>
</body></html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `cravzo-invoice-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button
      type="button"
      onClick={handleDownload}
      className="flex w-full items-center justify-center gap-2 rounded-2xl border-2 border-indigo-200 bg-indigo-50 px-4 py-3 text-sm font-bold text-indigo-700 transition hover:bg-indigo-100 active:scale-95"
    >
      <Receipt className="h-4 w-4" />
      Download Invoice (Tax Breakdown)
    </button>
  );
};

const TaxBreakdown = ({ pricing, distanceKm, isOpen, onToggle }) => (
  <div className="rounded-2xl bg-slate-50">
    <button
      type="button"
      onClick={onToggle}
      className="flex w-full items-center justify-between p-4 text-sm font-bold text-slate-800"
    >
      <span>Delivery & Tax</span>
      <span className="flex items-center gap-2">
        {formatCurrency(pricing.deliveryTotal + pricing.foodGst + pricing.packagingTax + pricing.platformFee)}
        {isOpen ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
      </span>
    </button>
    {isOpen && (
      <div className="px-4 pb-4 space-y-1.5 text-xs text-slate-500 border-t border-slate-200 pt-3">
        <div className="flex justify-between">
          <span>Delivery ({distanceKm.toFixed(1)} km)</span>
          <span>{formatCurrency(pricing.deliveryBase)}</span>
        </div>
        <div className="flex justify-between">
          <span>Food GST (5%)</span>
          <span>{formatCurrency(pricing.foodGst + pricing.packagingTax)}</span>
        </div>
        <div className="flex justify-between">
          <span>Delivery GST (18%)</span>
          <span>{formatCurrency(pricing.deliveryGst)}</span>
        </div>
        <div className="flex justify-between">
          <span>Platform Fee (incl. GST)</span>
          <span>{formatCurrency(pricing.platformFee)}</span>
        </div>
        <div className="border-t border-slate-200 pt-1.5 mt-1.5 flex justify-between font-medium text-slate-600">
          <span>CGST (50%)</span>
          <span>{formatCurrency(pricing.cgst)}</span>
        </div>
        <div className="flex justify-between font-medium text-slate-600">
          <span>SGST (50%)</span>
          <span>{formatCurrency(pricing.sgst)}</span>
        </div>
      </div>
    )}
  </div>
);

const Cart = () => {
  const navigate = useNavigate();
  const [cart, setCart] = useState([]);
  const [restaurant, setRestaurant] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showTaxBreakup, setShowTaxBreakup] = useState(false);

  useEffect(() => {
    const stored = JSON.parse(localStorage.getItem("cravzoCart"));
    if (stored && stored.length > 0) {
      setCart(stored);
      const restaurantId = stored[0]?.restaurantId;
      if (restaurantId) {
        getRestaurantById(restaurantId)
          .then(setRestaurant)
          .catch(() => setRestaurant(null))
          .finally(() => setLoading(false));
      } else {
        setLoading(false);
      }
    } else {
      setLoading(false);
    }
  }, []);

  const distanceKm = 3;

  const updateCart = (newCart) => {
    setCart(newCart);
    localStorage.setItem("cravzoCart", JSON.stringify(newCart));
    window.dispatchEvent(new Event("cartChange"));
  };

  const increase = (id) => {
    updateCart(cart.map((item) => (item.id === id ? { ...item, quantity: item.quantity + 1 } : item)));
  };

  const decrease = (id) => {
    updateCart(
      cart
        .map((item) => (item.id === id ? { ...item, quantity: item.quantity - 1 } : item))
        .filter((item) => item.quantity > 0),
    );
  };

  const removeItem = (id) => {
    updateCart(cart.filter((item) => item.id !== id));
  };

  const pricing = useMemo(() => {
    const itemTotal = cart.reduce((acc, item) => acc + getPrice(item.price) * item.quantity, 0);
    const deliveryBase = calculateDeliveryBase(distanceKm);
    const deliveryGst = deliveryBase * DELIVERY_GST_RATE;
    const deliveryTotal = deliveryBase + deliveryGst;
    const packagingFeeBase = Math.floor(itemTotal * PACKAGING_PERCENT);
    const foodGst = itemTotal * FOOD_GST_RATE;
    const packagingTax = packagingFeeBase * FOOD_GST_RATE;
    const platformFee = PLATFORM_FEE;
    const platformBase = PLATFORM_FEE / (1 + DELIVERY_GST_RATE);
    const platformTax = PLATFORM_FEE - platformBase;
    const totalTax = foodGst + packagingTax + deliveryGst + platformTax;
    const grandTotal = itemTotal + foodGst + packagingFeeBase + packagingTax + deliveryTotal + PLATFORM_FEE;
    const cgst = totalTax / 2;
    const sgst = totalTax / 2;

    return {
      itemTotal, deliveryBase, deliveryGst, deliveryTotal,
      packagingFeeBase, packagingTax, foodGst,
      platformFee, platformBase, platformTax,
      totalTax, grandTotal, cgst, sgst,
    };
  }, [cart, distanceKm]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-50">
        <div className="text-slate-400 animate-pulse">Loading cart...</div>
      </div>
    );
  }

  if (cart.length === 0) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-slate-50 p-4">
        <div className="mb-6 text-6xl">🛒</div>
        <h2 className="text-2xl font-bold text-slate-900">Your cart is empty</h2>
        <p className="mt-2 text-slate-500">Add some delicious items to get started!</p>
        <button
          onClick={() => navigate("/")}
          className="mt-6 rounded-2xl bg-indigo-600 px-8 py-3 font-bold text-white shadow-lg shadow-indigo-200 transition hover:bg-indigo-700 active:scale-95"
        >
          Browse Restaurants
        </button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 pb-32 md:pb-8 mt-14 md:mt-0">
      <div className="sticky top-14 md:top-0 z-30 bg-white shadow-sm">
        <div className="mx-auto flex max-w-3xl items-center gap-4 px-4 py-4">
          <button onClick={() => navigate(-1)} className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-100">
            <ChevronLeft className="h-5 w-5" />
          </button>
          <div>
            <h1 className="text-xl font-extrabold text-slate-900">Your Cart</h1>
            {restaurant && <p className="text-sm text-slate-500">{restaurant.name}</p>}
          </div>
        </div>
      </div>

      <div className="mx-auto max-w-3xl px-4 py-6">
        <div className="space-y-4">
          {cart.map((item) => (
            <div key={item.id} className="rounded-3xl bg-white p-5 shadow-sm transition-all">
              <div className="flex items-center gap-4">
                {item.imageUrl && (
                  <img src={item.imageUrl} alt={item.name} className="h-16 w-16 rounded-2xl object-cover" />
                )}
                <div className="flex-1 min-w-0">
                  <p className="font-bold text-slate-900 truncate">{item.name}</p>
                  <p className="text-sm text-slate-500">{formatCurrency(getPrice(item.price))} each</p>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => decrease(item.id)}
                    className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-100 text-slate-600 transition hover:bg-slate-200"
                  >
                    <Minus className="h-4 w-4" />
                  </button>
                  <span className="w-8 text-center font-bold text-slate-900">{item.quantity}</span>
                  <button
                    onClick={() => increase(item.id)}
                    className="flex h-8 w-8 items-center justify-center rounded-full bg-indigo-100 text-indigo-600 transition hover:bg-indigo-200"
                  >
                    <Plus className="h-4 w-4" />
                  </button>
                </div>
                <div className="text-right min-w-[70px]">
                  <p className="font-bold text-slate-900">{formatCurrency(getPrice(item.price) * item.quantity)}</p>
                </div>
                <button
                  onClick={() => removeItem(item.id)}
                  className="flex h-8 w-8 items-center justify-center rounded-full bg-rose-50 text-rose-500 transition hover:bg-rose-100"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-6 rounded-3xl bg-white p-6 shadow-sm">
          <h2 className="mb-4 flex items-center gap-2 text-lg font-bold text-slate-900">
            <Receipt className="h-5 w-5 text-indigo-600" />
            Price Breakdown
          </h2>

          <div className="space-y-3">
            <div className="flex justify-between text-sm">
              <span className="text-slate-600">Item Total</span>
              <span className="font-medium">{formatCurrency(pricing.itemTotal)}</span>
            </div>

            {pricing.packagingFeeBase > 0 && (
              <div className="flex justify-between text-sm">
                <span className="text-slate-600">Packaging</span>
                <span className="font-medium">{formatCurrency(pricing.packagingFeeBase)}</span>
              </div>
            )}

            <TaxBreakdown
              pricing={pricing}
              distanceKm={distanceKm}
              isOpen={showTaxBreakup}
              onToggle={() => setShowTaxBreakup(!showTaxBreakup)}
            />

            <div className="border-t-2 border-indigo-600 pt-3">
              <div className="flex justify-between text-base font-bold text-slate-900">
                <span>Grand Total</span>
                <span>{formatCurrency(pricing.grandTotal)}</span>
              </div>
            </div>

            <InvoiceDownload
              cart={cart}
              itemTotal={pricing.itemTotal}
              packagingFeeBase={pricing.packagingFeeBase}
              foodGst={pricing.foodGst}
              packagingTax={pricing.packagingTax}
              deliveryBase={pricing.deliveryBase}
              deliveryGst={pricing.deliveryGst}
              platformFee={pricing.platformFee}
              platformBase={pricing.platformBase}
              platformTax={pricing.platformTax}
              totalTax={pricing.totalTax}
              grandTotal={pricing.grandTotal}
              distanceKm={distanceKm}
            />
          </div>
        </div>

        <button
          onClick={() => navigate("/checkout")}
          className="mt-6 w-full rounded-2xl bg-indigo-600 py-4 text-base font-extrabold text-white shadow-lg shadow-indigo-200 transition hover:bg-indigo-700 active:scale-95"
        >
          Proceed to Checkout — {formatCurrency(pricing.grandTotal)}
        </button>
      </div>
    </div>
  );
};

export default Cart;