export const CUSTOMER_TAB_BAR_HEIGHT = 88;
export const TAB_SCREEN_BOTTOM_PADDING = CUSTOMER_TAB_BAR_HEIGHT + 32;
export const ACTION_BAR_BOTTOM_PADDING = 128;
export const MODAL_BOTTOM_PADDING = 40;
