export const CUSTOMER_TAB_BAR_HEIGHT = 104;
export const TAB_SCREEN_BOTTOM_PADDING = CUSTOMER_TAB_BAR_HEIGHT + 40;
export const ACTION_BAR_BOTTOM_PADDING = 168;
export const MODAL_BOTTOM_PADDING = 56;
export const MIN_DEVICE_NAV_GAP = 8;
export const MIN_BOTTOM_BAR_PADDING = 28;
